
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret   # Pull frontend image from ECR
      containers:
      - name: frontend
        image: <ECR IMAGE PATH>     # Your frontend React image
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://YOUR_URL.study/api/tasks"
        ports:
        - containerPort: 3000       # React app runs on port 3000
