apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: three-tier
spec: 
  type: ClusterIP                # Internal service (not exposed externally)
  ports:
  - port: 3500
    protocol: TCP
  selector:
    role: api                     # Select backend pods
