apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: three-tier
spec:
  capacity: 
    storage: 1Gi                # Storage size for MongoDB data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce             # Mounted by a single node
  hostPath:                     # Store data on node's filesystem (good for dev, not prod)
    path: /data/db
