apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
  namespace: three-tier
spec: 
  accessModes:  
    - ReadWriteOnce             # Request RWO access
  storageClassName: ""          # Empty means bind to static PV
  resources:
    requests:
      storage: 1Gi              # Request 1Gi storage
