apiVersion: v1
kind: Service
metadata:
  namespace: three-tier
  name: mongodb-svc
spec:
  selector:
    app: mongodb                # Connect service to pods with label app=mongodb
  ports:
  - name: mongodb-svc
    protocol: TCP
    port: 27017                 # Service port
    targetPort: 27017           # Forward to MongoDB container port
